### ISSUE TITLE
Python 3 support ( if someone can provide a complete PyQt5 package )

### ISSUE THREAD

**Issue by bruce30262** [bruce30262/Python_editor#2]
So far the editor works fine in IDA Pro v7.0 ~ v7.2 ( maybe v7.3 ) .  
However it won't work in IDA that uses Python 3 and the new APIs ( >= v7.4 ).  
For Python 3 solution, [this post](http://techbliss.org/threads/ida-pro-python-editor-by-storm-shadow.718/page-2#post-3647) from jinoweb provides the fixes for IDA 7.4 & python3. Although jinoweb also provided a [PyQt5 package for Python 3](http://techbliss.org/threads/pyqt5-for-ida-7-4-python3.997/), however the package is missing Qsci.dll, which is required for the editor, and because of this I couldn't get the editor work in python3 IDA.  

I would love to continue this project. However I'll need a complete PyQt5 package for Python 3, at least a working Qsci.dll ( well maybe I can build it on my own ? But it'll take a lot of times and disk space... ). Until then, it's better just run the editor in IDA <= v7.3.

**Comment by Alexpux** [comment]
@bruce30262 under Windows it is Qsci.pyd and you can find it under Lib/site-packages/PyQt5

**Comment by bruce30262** [comment]
@Alexpux thx for the info, I'll take a look when I got time

**Comment by bruce30262** [comment]
Was able to use [Dependencies](https://github.com/lucasg/Dependencies) to figure out the missing dll : `qscintilla2_qt5.dll`. Just copy the dll to the PyQt5 folder and we're good to go. After some programming work, [v3.0](https://github.com/bruce30262/Python_editor/releases/tag/3.0) was released :) However I can't figure out how to get the editor to work with [idapkg](https://github.com/Jinmo/idapkg) ( see #3 ), will have to deal with that later.
